export type GoogleLanguage = keyof typeof GoogleLanguages;
export type DeeplLanguage = keyof typeof DeeplLanguages;
export type KagiLanguage = keyof typeof KagiLanguages;
export declare const GoogleLanguages: {
    readonly auto: "Detect language";
    readonly af: "Afrikaans";
    readonly sq: "Albanian";
    readonly am: "Amharic";
    readonly ar: "Arabic";
    readonly hy: "Armenian";
    readonly as: "Assamese";
    readonly ay: "Aymara";
    readonly az: "Azerbaijani";
    readonly bm: "Bambara";
    readonly eu: "Basque";
    readonly be: "Belarusian";
    readonly bn: "Bengali";
    readonly bho: "Bhojpuri";
    readonly bs: "Bosnian";
    readonly bg: "Bulgarian";
    readonly ca: "Catalan";
    readonly ceb: "Cebuano";
    readonly ny: "Chichewa";
    readonly "zh-CN": "Chinese (Simplified)";
    readonly "zh-TW": "Chinese (Traditional)";
    readonly co: "Corsican";
    readonly hr: "Croatian";
    readonly cs: "Czech";
    readonly da: "Danish";
    readonly dv: "Dhivehi";
    readonly doi: "Dogri";
    readonly nl: "Dutch";
    readonly en: "English";
    readonly eo: "Esperanto";
    readonly et: "Estonian";
    readonly ee: "Ewe";
    readonly tl: "Filipino";
    readonly fi: "Finnish";
    readonly fr: "French";
    readonly fy: "Frisian";
    readonly gl: "Galician";
    readonly ka: "Georgian";
    readonly de: "German";
    readonly el: "Greek";
    readonly gn: "Guarani";
    readonly gu: "Gujarati";
    readonly ht: "Haitian Creole";
    readonly ha: "Hausa";
    readonly haw: "Hawaiian";
    readonly iw: "Hebrew";
    readonly hi: "Hindi";
    readonly hmn: "Hmong";
    readonly hu: "Hungarian";
    readonly is: "Icelandic";
    readonly ig: "Igbo";
    readonly ilo: "Ilocano";
    readonly id: "Indonesian";
    readonly ga: "Irish";
    readonly it: "Italian";
    readonly ja: "Japanese";
    readonly jw: "Javanese";
    readonly kn: "Kannada";
    readonly kk: "Kazakh";
    readonly km: "Khmer";
    readonly rw: "Kinyarwanda";
    readonly gom: "Konkani";
    readonly ko: "Korean";
    readonly kri: "Krio";
    readonly ku: "Kurdish (Kurmanji)";
    readonly ckb: "Kurdish (Sorani)";
    readonly ky: "Kyrgyz";
    readonly lo: "Lao";
    readonly la: "Latin";
    readonly lv: "Latvian";
    readonly ln: "Lingala";
    readonly lt: "Lithuanian";
    readonly lg: "Luganda";
    readonly lb: "Luxembourgish";
    readonly mk: "Macedonian";
    readonly mai: "Maithili";
    readonly mg: "Malagasy";
    readonly ms: "Malay";
    readonly ml: "Malayalam";
    readonly mt: "Maltese";
    readonly mi: "Maori";
    readonly mr: "Marathi";
    readonly "mni-Mtei": "Meiteilon (Manipuri)";
    readonly lus: "Mizo";
    readonly mn: "Mongolian";
    readonly my: "Myanmar (Burmese)";
    readonly ne: "Nepali";
    readonly no: "Norwegian";
    readonly or: "Odia (Oriya)";
    readonly om: "Oromo";
    readonly ps: "Pashto";
    readonly fa: "Persian";
    readonly pl: "Polish";
    readonly pt: "Portuguese";
    readonly pa: "Punjabi";
    readonly qu: "Quechua";
    readonly ro: "Romanian";
    readonly ru: "Russian";
    readonly sm: "Samoan";
    readonly sa: "Sanskrit";
    readonly gd: "Scots Gaelic";
    readonly nso: "Sepedi";
    readonly sr: "Serbian";
    readonly st: "Sesotho";
    readonly sn: "Shona";
    readonly sd: "Sindhi";
    readonly si: "Sinhala";
    readonly sk: "Slovak";
    readonly sl: "Slovenian";
    readonly so: "Somali";
    readonly es: "Spanish";
    readonly su: "Sundanese";
    readonly sw: "Swahili";
    readonly sv: "Swedish";
    readonly tg: "Tajik";
    readonly ta: "Tamil";
    readonly tt: "Tatar";
    readonly te: "Telugu";
    readonly th: "Thai";
    readonly ti: "Tigrinya";
    readonly ts: "Tsonga";
    readonly tr: "Turkish";
    readonly tk: "Turkmen";
    readonly ak: "Twi";
    readonly uk: "Ukrainian";
    readonly ur: "Urdu";
    readonly ug: "Uyghur";
    readonly uz: "Uzbek";
    readonly vi: "Vietnamese";
    readonly cy: "Welsh";
    readonly xh: "Xhosa";
    readonly yi: "Yiddish";
    readonly yo: "Yoruba";
    readonly zu: "Zulu";
};
export declare const DeeplLanguages: {
    readonly "": "Detect language";
    readonly ace: "Acehnese";
    readonly af: "Afrikaans";
    readonly sq: "Albanian";
    readonly ar: "Arabic";
    readonly an: "Aragonese";
    readonly hy: "Armenian";
    readonly as: "Assamese";
    readonly ay: "Aymara";
    readonly az: "Azerbaijani";
    readonly ba: "Bashkir";
    readonly eu: "Basque";
    readonly be: "Belarusian";
    readonly bn: "Bengali";
    readonly bho: "Bhojpuri";
    readonly bs: "Bosnian";
    readonly br: "Breton";
    readonly bg: "Bulgarian";
    readonly my: "Burmese";
    readonly yue: "Cantonese";
    readonly ca: "Catalan";
    readonly ceb: "Cebuano";
    readonly "zh-hans": "Chinese (Simplified)";
    readonly "zh-hant": "Chinese (Traditional)";
    readonly hr: "Croatian";
    readonly cs: "Czech";
    readonly da: "Danish";
    readonly prs: "Dari";
    readonly nl: "Dutch";
    readonly "en-us": "English (American)";
    readonly "en-gb": "English (British)";
    readonly eo: "Esperanto";
    readonly et: "Estonian";
    readonly fi: "Finnish";
    readonly fr: "French";
    readonly gl: "Galician";
    readonly ka: "Georgian";
    readonly de: "German";
    readonly el: "Greek";
    readonly gn: "Guarani";
    readonly gu: "Gujarati";
    readonly ht: "Haitian Creole";
    readonly ha: "Hausa";
    readonly he: "Hebrew";
    readonly hi: "Hindi";
    readonly hu: "Hungarian";
    readonly is: "Icelandic";
    readonly ig: "Igbo";
    readonly id: "Indonesian";
    readonly ga: "Irish";
    readonly it: "Italian";
    readonly ja: "Japanese";
    readonly jv: "Javanese";
    readonly ko: "Korean";
    readonly pam: "Kapampangan";
    readonly kk: "Kazakh";
    readonly kmr: "Kurdish (Kurmanji)";
    readonly ckb: "Kurdish (Sorani)";
    readonly ky: "Kyrgyz";
    readonly lo: "Lao";
    readonly la: "Latin";
    readonly lv: "Latvian";
    readonly ln: "Lingala";
    readonly lt: "Lithuanian";
    readonly lmo: "Lombard";
    readonly lb: "Luxembourgish";
    readonly mk: "Macedonian";
    readonly mai: "Maithili";
    readonly mg: "Malagasy";
    readonly ms: "Malay";
    readonly ml: "Malayalam";
    readonly mt: "Maltese";
    readonly mi: "Maori";
    readonly mr: "Marathi";
    readonly mn: "Mongolian";
    readonly ne: "Nepali";
    readonly nb: "Norwegian (Bokmål)";
    readonly oc: "Occitan";
    readonly om: "Oromo";
    readonly pag: "Pangasinan";
    readonly ps: "Pashto";
    readonly fa: "Persian";
    readonly pl: "Polish";
    readonly "pt-br": "Portuguese (Brazilian)";
    readonly "pt-pt": "Portuguese (European)";
    readonly pa: "Punjabi";
    readonly qu: "Quechua";
    readonly ro: "Romanian";
    readonly ru: "Russian";
    readonly sm: "Samoan";
    readonly sa: "Sanskrit";
    readonly gd: "Scottish Gaelic";
    readonly sr: "Serbian";
    readonly st: "Sesotho";
    readonly sn: "Shona";
    readonly scn: "Sicilian";
    readonly sd: "Sindhi";
    readonly si: "Sinhala";
    readonly sk: "Slovak";
    readonly sl: "Slovenian";
    readonly so: "Somali";
    readonly es: "Spanish";
    readonly "es-419": "Spanish (Latin American)";
    readonly su: "Sundanese";
    readonly sw: "Swahili";
    readonly sv: "Swedish";
    readonly tl: "Tagalog";
    readonly tg: "Tajik";
    readonly ta: "Tamil";
    readonly tt: "Tatar";
    readonly te: "Telugu";
    readonly th: "Thai";
    readonly ti: "Tigrinya";
    readonly ts: "Tsonga";
    readonly tn: "Tswana";
    readonly tr: "Turkish";
    readonly tk: "Turkmen";
    readonly uk: "Ukrainian";
    readonly ur: "Urdu";
    readonly ug: "Uyghur";
    readonly uz: "Uzbek";
    readonly vi: "Vietnamese";
    readonly cy: "Welsh";
    readonly wo: "Wolof";
    readonly xh: "Xhosa";
    readonly yi: "Yiddish";
    readonly yo: "Yoruba";
    readonly zu: "Zulu";
};
export declare function deeplLanguageToGoogleLanguage(language: string): string;
export declare const KagiLanguages: {
    readonly auto: "Detect language";
    readonly om: "(Afan)/Oromoor/Oriya";
    readonly ab: "Abkhazian";
    readonly ace: "Acehnese";
    readonly ach: "Acholi";
    readonly aa: "Afar";
    readonly af: "Afrikaans";
    readonly ak: "Akan";
    readonly sq: "Albanian";
    readonly alz: "Alur";
    readonly am: "Amharic";
    readonly ar: "Arabic";
    readonly an: "Aragonese";
    readonly hy: "Armenian";
    readonly as: "Assamese";
    readonly av: "Avaric";
    readonly ae: "Avestan";
    readonly ava: "Awadhi";
    readonly ay: "Aymara";
    readonly az: "Azerbaijani";
    readonly ban: "Balinese";
    readonly bal: "Baluchi";
    readonly bm: "Bambara";
    readonly bci: "Baoulé";
    readonly ba: "Bashkir";
    readonly eu: "Basque";
    readonly btk: "Batak";
    readonly bar: "Bavarian";
    readonly be: "Belarusian";
    readonly bem: "Bemba";
    readonly bn: "Bengali";
    readonly bew: "Betawi";
    readonly bho: "Bhojpuri";
    readonly dz: "Bhutani";
    readonly bh: "Bihari";
    readonly bcl: "Bikol";
    readonly bi: "Bislama";
    readonly bs: "Bosnian";
    readonly br: "Breton";
    readonly bg: "Bulgarian";
    readonly my: "Burmese";
    readonly bua: "Buryat";
    readonly km: "Cambodian";
    readonly yue: "Cantonese";
    readonly ca: "Catalan";
    readonly ceb: "Cebuano";
    readonly ch: "Chamorro";
    readonly ce: "Chechen";
    readonly chr: "Cherokee";
    readonly ny: "Chichewa";
    readonly zh_cn: "Chinese (Simplified)";
    readonly zh_tw: "Chinese (Traditional)";
    readonly cu: "Church Slavonic";
    readonly chk: "Chuukese";
    readonly cv: "Chuvash";
    readonly kw: "Cornish";
    readonly co: "Corsican";
    readonly cr: "Cree";
    readonly crh: "Crimean Tatar";
    readonly hr: "Croatian";
    readonly cs: "Czech";
    readonly da: "Danish";
    readonly din: "Dinka";
    readonly div: "Divehi";
    readonly doi: "Dogri";
    readonly dov: "Dombe";
    readonly nl: "Dutch";
    readonly dyu: "Dyula";
    readonly en_gb: "English (UK)";
    readonly en_us: "English (US)";
    readonly eo: "Esperanto";
    readonly et: "Estonian";
    readonly ee: "Ewe";
    readonly fo: "Faroese";
    readonly fj: "Fiji";
    readonly fil: "Filipino";
    readonly fi: "Finnish";
    readonly fon: "Fon";
    readonly fr: "French";
    readonly fy: "Frisian";
    readonly fur: "Friulian";
    readonly ff: "Fulah";
    readonly gaa: "Ga";
    readonly gl: "Galician";
    readonly lg: "Ganda";
    readonly ka: "Georgian";
    readonly de: "German";
    readonly hac: "Gorani (Hawrami)";
    readonly el: "Greek";
    readonly kl: "Greenlandic";
    readonly gn: "Guarani";
    readonly gu: "Gujarati";
    readonly ht: "Haitian";
    readonly ha: "Hausa";
    readonly haw: "Hawaiian";
    readonly he: "Hebrew";
    readonly hz: "Herero";
    readonly hil: "Hiligaynon";
    readonly hi: "Hindi";
    readonly ho: "Hiri Motu";
    readonly hu: "Hungarian";
    readonly hrx: "Hunsrik";
    readonly iba: "Iban";
    readonly is: "Icelandic";
    readonly io: "Ido";
    readonly ig: "Igbo";
    readonly ilo: "Ilocano";
    readonly id: "Indonesian";
    readonly ia: "Interlingua";
    readonly ie: "Interlingue";
    readonly iu: "Inuktitut";
    readonly ik: "Inupiak";
    readonly ga: "Irish Gaelic";
    readonly it: "Italian";
    readonly jam: "Jamaican Patois";
    readonly ja: "Japanese";
    readonly jv: "Javanese";
    readonly cpe: "Jingpo";
    readonly kn: "Kannada";
    readonly kr: "Kanuri";
    readonly ks: "Kashmiri";
    readonly kk: "Kazakh";
    readonly kha: "Khasi";
    readonly ki: "Kikuyu";
    readonly rw: "Kinyarwanda";
    readonly ky: "Kirghiz";
    readonly rn: "Kirundi";
    readonly ktu: "Kituba";
    readonly kv: "Komi";
    readonly kg: "Kongo";
    readonly kok: "Konkani";
    readonly ko: "Korean";
    readonly kj: "Kuanyama";
    readonly ku: "Kurdish (Kurmanji)";
    readonly ckb: "Kurdish (Sorani)";
    readonly sdh: "Kurdish (Xwarin)";
    readonly lo: "Laothian";
    readonly ltg: "Latgalian";
    readonly la: "Latin";
    readonly lv: "Latvian";
    readonly lij: "Ligurian";
    readonly li: "Limburgan";
    readonly lim: "Limburgish";
    readonly ln: "Lingala";
    readonly lt: "Lithuanian";
    readonly lmo: "Lombard";
    readonly lu: "Luba_Katanga";
    readonly luo: "Luo";
    readonly lb: "Luxembourgish";
    readonly mk: "Macedonian";
    readonly mad: "Madurese";
    readonly mai: "Maithili";
    readonly mak: "Makassar";
    readonly mg: "Malagasy";
    readonly ms: "Malay";
    readonly ml: "Malayalam";
    readonly mt: "Maltese";
    readonly gv: "Manx Gaelic";
    readonly mi: "Maori";
    readonly mr: "Marathi";
    readonly mh: "Marshallese";
    readonly mwr: "Marwadi";
    readonly mo: "Moldavian";
    readonly mn: "Mongolian";
    readonly cnr: "Montenegrin";
    readonly nqo: "NKo";
    readonly nhe: "Nahuatl";
    readonly na: "Nauru";
    readonly nv: "Navajo";
    readonly ndc: "Ndau";
    readonly ng: "Ndonga";
    readonly new: "Nepalbhasa";
    readonly ne: "Nepali";
    readonly nd: "North Ndebele";
    readonly se: "Northern Sami";
    readonly ns: "Northern Sotho";
    readonly no: "Norwegian";
    readonly nb: "Norwegian (Bokmål)";
    readonly nn: "Norwegian (Nynorsk)";
    readonly nus: "Nuer";
    readonly oc: "Occitan";
    readonly oj: "Ojibwa";
    readonly or: "Oriya";
    readonly os: "Ossetian";
    readonly pi: "Pali";
    readonly pag: "Pangasinan";
    readonly pap: "Papiamento";
    readonly ps: "Pashto/Pushto";
    readonly fa: "Persian";
    readonly pl: "Polish";
    readonly pt_br: "Portuguese (Brazil)";
    readonly pt_pt: "Portuguese (Portugal)";
    readonly pa: "Punjabi";
    readonly qu: "Quechua";
    readonly kek: "Qʼeqchiʼ";
    readonly rm: "Rhaeto_Romanic";
    readonly rom: "Romani";
    readonly ro: "Romanian";
    readonly ru: "Russian";
    readonly sm: "Samoan";
    readonly sg: "Sangro";
    readonly sa: "Sanskrit";
    readonly sat: "Santali";
    readonly sc: "Sardinian";
    readonly sco: "Scots";
    readonly gd: "Scottish Gaelic";
    readonly sr: "Serbian";
    readonly sh: "Serbo_Croatian";
    readonly st: "Sesotho";
    readonly seto: "Seto";
    readonly shn: "Shan";
    readonly sn: "Shona";
    readonly ii: "Sichuan Yi";
    readonly scn: "Sicilian";
    readonly szl: "Silesian";
    readonly sd: "Sindhi";
    readonly si: "Sinhalese";
    readonly ss: "Siswati";
    readonly sk: "Slovak";
    readonly sl: "Slovenian";
    readonly so: "Somali";
    readonly sb: "Sorbian";
    readonly nr: "South Ndebele";
    readonly sma: "Southern Sami";
    readonly es: "Spanish";
    readonly su: "Sundanese";
    readonly sus: "Susu";
    readonly sx: "Sutu";
    readonly sw: "Swahili";
    readonly sv: "Swedish";
    readonly gsw: "Swiss German";
    readonly syr: "Syriac";
    readonly tl: "Tagalog";
    readonly ty: "Tahitian";
    readonly tg: "Tajik";
    readonly ta: "Tamil";
    readonly tt: "Tatar";
    readonly te: "Telugu";
    readonly tet: "Tetum";
    readonly th: "Thai";
    readonly bo: "Tibetan";
    readonly ti: "Tigrinya";
    readonly tiv: "Tiv";
    readonly tpi: "Tok Pisin";
    readonly to: "Tonga";
    readonly ts: "Tsonga";
    readonly tn: "Tswana";
    readonly tum: "Tumbuka";
    readonly tr: "Turkish";
    readonly tk: "Turkmen";
    readonly tyv: "Tuvan";
    readonly tw: "Twi";
    readonly udm: "Udmurt";
    readonly ug: "Uighur";
    readonly uk: "Ukrainian";
    readonly ur: "Urdu";
    readonly uz: "Uzbek";
    readonly ve: "Venda";
    readonly vec: "Venetian";
    readonly vi: "Vietnamese";
    readonly vo: "Volapuk";
    readonly vro: "Võro";
    readonly wa: "Walloon";
    readonly war: "Waray";
    readonly cy: "Welsh";
    readonly wo: "Wolof";
    readonly xh: "Xhosa";
    readonly sah: "Yakut";
    readonly yi: "Yiddish";
    readonly yo: "Yoruba";
    readonly yua: "Yucatec Maya";
    readonly zap: "Zapotec";
    readonly diq: "Zazaki";
    readonly za: "Zhuang";
    readonly zu: "Zulu";
};
