export declare const getCloudSyncDirection: () => string;
export declare const setCloudSyncDirection: (direction: "push" | "pull" | "both" | "manual") => void;
export declare const areLocalSettingsDirty: () => boolean;
export declare const markLocalSettingsDirty: () => void;
export declare const markLocalSettingsClean: () => void;
export declare function shouldCloudSync(direction: "push" | "pull"): boolean;
export declare function putCloudSettings(manual?: boolean): Promise<void>;
export declare function getCloudSettings(shouldNotify?: boolean, force?: boolean): Promise<boolean>;
export declare function deleteCloudSettings(): Promise<void>;
export declare function eraseAllCloudData(): Promise<void>;
